format = """\
$username[@](bold yellow)$hostname $git_branch
$directory
$character
"""

[username]
show_always = true
style_user = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold green"
format = "[$hostname]($style)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold green)"

[directory]
truncation_length = 8
truncate_to_repo = false
truncation_symbol = ".../"

[git_branch]
format = "[$symbol$branch]($style)"
